### ISSUE TITLE
请问svelte 内全局怎么引入？

### ISSUE THREAD

**Issue by ahe-qyss** [lb-tools/lb-toast#1]

**Comment by lblblong** [comment]
可以直接下载 dist 下的 index.css 和 index.js 引入，也可以 npm install lb-toast 安装后直接使用

**Comment by lblblong** [comment]
npm install lb-toast 后，在项目的任何地方都可以直接调用：
```typescript
import Toast from "lb-toast"
Toast.info("普通信息 toast")
```

**Comment by ahe-qyss** [comment]
我用的npm 单个引入  没有问题  我引入css 就会报错 应该是我引入问题

**Comment by lblblong** [comment]
```typescript
import "lb-toast/dist/index.css"
```

这句有全局添加吗

**Comment by ahe-qyss** [comment]
app 引入index.css报错   是不是因为 rollup.config.js 配置问题

**Comment by lblblong** [comment]
如果 node_modules 下 lb-toast/dist/index.css 文件存在，那应该就是你项目配置的问题
